/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mozeeza_repeater_Decoder_DecodeHeader */

#ifndef _Included_com_mozeeza_repeater_Decoder_DecodeHeader
#define _Included_com_mozeeza_repeater_Decoder_DecodeHeader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
