/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mozeeza_repeater_Decoder */

#ifndef _Included_com_mozeeza_repeater_Decoder
#define _Included_com_mozeeza_repeater_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mozeeza_repeater_Decoder
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mozeeza_repeater_Decoder_decode
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
